include $(MWD)/../Makefile
R2R_PD = $(R2R_DIR)/$(PLATFORM)
TARGET := $(R2R_PD)/$(APP)

CFILES := $(CFILES_COMMON) $(CFILES_$(PLATFORM))
HFILES := $(HFILES_COMMON) $(HFILES_$(PLATFORM))
AFILES := $(AFILES_COMMON) $(AFILES_$(PLATFORM))

BUILD_DIR = build
OBJ_DIR := $(BUILD_DIR)/$(PLATFORM)_obj
OBJS := $(addprefix $(OBJ_DIR)/, $(CFILES:.c=.o) $(AFILES:.s=.o))

MKDIR_P ?= mkdir -p
